#================================================================================================================
# Multiple round inference YAML configuration file - Based on Table 1 of Barret & Dupourqué (2024, A&A) (model 2)
# This yaml file shows the use of a coarse inference restrictor coupled with multiple round inference.
# The model has 5 parameters, so the training sample cannot be too limited, but with 5 parameters, we show that good
# results are obtained with 5 rounds of 1000 samples each.
# D. Barret 21/02/2024
#================================================================================================================
path_pha: "SIXSA_REFERENCE_SPECTRA/"
path_outputs : "SIXSA_OUTPUTS/"
reference_pha : "pre_burst_spectrum_opt.pha"
energy_range : [0.3,10.] # energy range for the fit
jaxspec_model_expression : "Tbabs() * (Powerlaw()+Blackbodyrad())" # see jaxspec documentation
parameter_lower_bounds : [0.15 , 1.0 , 0.1, 0.3,100.]
parameter_upper_bounds : [0.35 , 3.0 , 10.0, 3.0,1000.]
parameter_prior_types : ["Uniform" , "Uniform" , "Uniform","Uniform","Uniform"]
parameter_states : ["free" , "free" , "free", "free" , "free"]
parameter_names_for_plots : ["Nh" , "Gamma" , "Npl","kTbb","Nbb"]
restricted_prior_type : "coarse_inference_restricted_prior"
number_of_simulations_for_restricted_prior : 2000 # quite aggressive for getting the restricted prior of a model of 5 parameters
type_of_inference : "multiple round inference"
number_of_simulations_for_train_set : 1000 # very aggressive for fitting real data
number_of_rounds_for_multiple_inference : 5
number_of_posterior_samples : 20000

