#================================================================================================================
# Single round inference YAML configuration file - Based on Table 1 of Barret & Dupourqué (2024, A&A) (model 1)
# This yaml file shows the use of a restrictor based on the number of counts in the spectrum to be between 1000 and 10000
# coupled with single round inference. The reference spectrum has 2000 counts, with a constant grouping of 5
# consecutive channels, so that the spectrum ends up with 200 bins or so.
# D. Barret 21/02/2024
#================================================================================================================
path_pha: "SIXSA_REFERENCE_SPECTRA/"
path_outputs : "SIXSA_OUTPUTS/"
reference_pha : "Reference_pha_tbabs_powerlaw_2000counts_groupconstant_5.pha"
energy_range : [0.3,10.] # energy range for the fit
jaxspec_model_expression : "Tbabs() * (Powerlaw())"
parameter_lower_bounds : [0.1 , 0.5 , 0.01]
parameter_upper_bounds : [0.3 , 2.5 , 100.0]
parameter_prior_types : ["LogUniform" , "Uniform" , "LogUniform"]
parameter_states : ["free" , "free" , "free"]
parameter_names_for_plots : ["Nh" , "Gamma" , "Npl"]
restricted_prior_type : "cmin_cmax_restricted_prior"
number_of_rounds_for_restricted_prior : 10
number_of_simulations_for_restricted_prior : 2000
c_min_for_restricted_prior : 1000.
c_max_for_restricted_prior : 10000.
fraction_of_valid_simulations_to_stop_restricted_prior : 0.95
type_of_inference : "single round inference"
number_of_simulations_for_train_set : 20000
number_of_simulations_for_test_set : 500
number_of_posterior_samples : 20000