# Single round inference YAML configuration file - Based on Table 1 of Barret & Dupourqué (2024, A&A)
path_pha: "SIXSA_REFERENCE_SPECTRA/"
path_outputs : "SIXSA_OUTPUTS/"
reference_pha : "Reference_pha_tbabs_powerlaw_20000counts_groupconstant_5.pha"
energy_range : [0.3,10.] # energy range for the fit
jaxspec_model_expression : "Tbabs() * (Powerlaw())"
parameter_lower_bounds : [0.1 , 0.5 , 0.01]
parameter_upper_bounds : [0.3 , 2.5 , 100.0]
parameter_prior_types : ["Uniform" , "Uniform" , "LogUniform"]
parameter_states : ["free" , "free" , "free"]
parameter_names_for_plots : ["Nh" , "Gamma" , "Npl"]
restricted_prior_type : "coarse_inference_restricted_prior"
number_of_simulations_for_restricted_prior : 2500
type_of_inference : "single round inference"
number_of_simulations_for_train_set : 10000
number_of_simulations_for_test_set : 100
number_of_posterior_samples : 20000
