#================================================================================================================
# Multiple round inference YAML configuration file - Based on Table 1 of Barret & Dupourqué (2024, A&A)
# This one highlights the use of the restrictor based on the cstat. This is not the most efficient way
# to restrict the priors, but shows how to implement an arbitrary function to do so. For real data, the restrictor
# obtained from a quick and coarse inference is working very well.
# The spectrum is modeled by the sum of an absorbed power law and blackbody. Alternative models may fit the data better
# but at the time of the writing of the paper, those models were not available in jaxspec.
# D. Barret 21/02/2024
#================================================================================================================
path_pha: "SIXSA_REFERENCE_SPECTRA/"
path_outputs : "SIXSA_OUTPUTS/"
reference_pha : "pre_burst_spectrum_opt.pha" # Real data persistent pre-burst emission (see paper)
energy_range : [0.3,10.] # energy range for the fit
jaxspec_model_expression : "Tbabs() * (Powerlaw()+Blackbodyrad())" # see jaxspec documentation
parameter_lower_bounds : [0.15 , 1.0 , 0.1, 0.3,100.]
parameter_upper_bounds : [0.35 , 3.0 , 10.0, 3.0,1000.]
parameter_prior_types : ["Uniform" , "Uniform" , "Uniform","Uniform","Uniform"]
parameter_states : ["free" , "free" , "free", "free" , "free"]
parameter_names_for_plots : ["Nh" , "Gamma" , "Npl","kTbb","Nbb"]
restricted_prior_type : "cstat_restricted_prior"
number_of_rounds_for_restricted_prior : 2
number_of_simulations_for_restricted_prior : 10000
good_fraction_for_cstat_restricted_prior : 25. # The percentage of spectra providing the lowest cstat
type_of_inference : "multiple round inference"
number_of_simulations_for_train_set : 5000
number_of_rounds_for_multiple_inference : 5
number_of_posterior_samples : 20000

