# Multiple round inference YAML configuration file - Based on Table 1 of Barret & Dupourqué (2024, A&A)
path_pha: "SIXSA_REFERENCE_SPECTRA/"
path_outputs : "SIXSA_OUTPUTS/"
reference_pha : "pre_burst_spectrum_opt.pha"
energy_range : [0.3,10.] # energy range for the fit
jaxspec_model_expression : "Tbabs() * (Powerlaw()+Blackbodyrad())" # see jaxspec documentation
parameter_lower_bounds : [0.15 , 1.0 , 0.1, 0.3,100.]
parameter_upper_bounds : [0.35 , 3.0 , 10.0, 3.0,1000.]
parameter_prior_types : ["Uniform" , "Uniform" , "LogUniform","Uniform","LogUniform"]
parameter_states : ["free" , "free" , "free", "free" , "free"]
parameter_names_for_plots : ["Nh" , "Gamma" , "Npl","kTbb","Nbb"]
restricted_prior_type : 'cmin_cmax_restricted_prior'
number_of_rounds_for_restricted_prior : 10
number_of_simulations_for_restricted_prior : 5000
c_min_for_restricted_prior : 200000. # numbers could be set automatically from the pha file
c_max_for_restricted_prior : 250000. # numbers could be set automatically from the pha file
fraction_of_valid_simulations_to_stop_restricted_prior : 0.90
type_of_inference : "single round inference"
number_of_simulations_for_train_set : 100000
number_of_simulations_for_test_set : 500
number_of_posterior_samples : 20000