# Single round inference YAML configuration file - Based on Table 1 of Barret & Dupourqué (2024, A&A)
path_pha: "SIXSA_REFERENCE_SPECTRA/"
path_outputs : "SIXSA_OUTPUTS/"
reference_pha : "b_008_0.25s_raw_opt.pha"
energy_range : [0.3,10.] # energy range for the fit
jaxspec_model_expression : "Tbabs() * (Powerlaw()+Blackbodyrad())" # see jaxspec documentation
parameter_lower_bounds : [0.2 , 1.7 , 0.1, 0.1,0.1]
parameter_upper_bounds : [0.2 , 1.7 , 10.0, 4.5,100000.]
parameter_prior_types : ["Uniform" , "Uniform" , "LogUniform","Uniform","LogUniform"]
parameter_states : ["frozen" , "frozen" , "free", "free" , "free"]
parameter_names_for_plots : ["Nh" , "Gamma" , "Npl","kTbb","Nbb"]
restricted_prior_type : "coarse_inference_restricted_prior"
number_of_simulations_for_restricted_prior : 2000
type_of_inference : "single round inference"
number_of_simulations_for_train_set : 20000 # Aggressive (the training set was larger in the paper)
number_of_simulations_for_test_set : 100
number_of_posterior_samples : 20000