# Multiple round inference YAML configuration file - Based on Table 1 of Barret & Dupourqué (2024, A&A)
path_pha: "SIXSA_REFERENCE_SPECTRA/"
path_pdf_files : "SIXSA_OUTPUTS/"
filter_pha : "Reference_pha_tbabs_powerlaw_20000counts_groupconstant_5.pha"
root_output_pdf_filename : "SRI_spectrum_20000_"
energy_range : [0.3,10.] # energy range for the fit
jaxspec_model_expression : "Tbabs() * (Powerlaw())"
parameter_lower_bounds : [0.1 , 0.5 , 0.01]
parameter_upper_bounds : [0.3 , 2.5 , 100.0]
parameter_prior_types : ["LogUniform" , "Uniform" , "LogUniform"]
parameter_states : ["free" , "free" , "free"]
parameter_names_for_plots : ["Nh" , "Gamma" , "Npl"]
num_rounds_for_cmin_cmax_restrictor : 10
num_sim_for_cmin_cmax_restrictor : 500
cmin_for_cmin_cmax_restrictor : 10000.
cmax_for_cmin_cmax_restrictor : 100000.
fraction_of_valid_simulations_to_stop_restricted_prior : 0.95
number_of_simulations_for_train_set : 1000
number_of_rounds : 5
n_posterior_samples : 20000

