# Multiple round inference YAML configuration file - Based on Table 1 of Barret & Dupourqué (2024, A&A)
path_pha: "SIXSA_REFERENCE_SPECTRA/"
path_pdf_files : "SIXSA_OUTPUTS/"
filter_pha : "pre_burst_Tint200_no_bkg_no_sys_raw_opt.pha" # optimal grouping applied to the spectrum
root_output_pdf_filename : "MRI_real_data_"
energy_range : [0.3,10.] # energy range for the fit
jaxspec_model_expression : "Tbabs() * (Powerlaw()+Blackbodyrad())"
parameter_lower_bounds : [0.15 , 1.0 , 0.01, 0.3, 1.]
parameter_upper_bounds : [0.35 , 3.0 , 10.0, 3.0, 10000.]
parameter_prior_types : ["Uniform" , "Uniform" , "LogUniform","Uniform" , "LogUniform"]
parameter_states : ["free" , "free" , "free","free","free"]
parameter_names_for_plots : ["Nh" , "Gamma" , "Npl","kTbb","Nbb"]
num_rounds_for_cmin_cmax_restrictor : 10
num_sim_for_cmin_cmax_restrictor : 500
cmin_for_cmin_cmax_restrictor : 100000. # The spectrum contains about 200000 counts
cmax_for_cmin_cmax_restrictor : 300000.
fraction_of_valid_simulations_to_stop_restricted_prior : 0.95
number_of_simulations_for_train_set : 5000
number_of_rounds : 3
n_posterior_samples : 20000

